default:
  font: Ubuntu
  bold: "{* Bold}"
  mono: DejaVu Sans Mono
  prechap: "Chapter "
  postchap: ""
  presect: "Section "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Contents"
  fig: "Figure "
  tab: "Table "
  indent: "\\qquad"
  thanks: "This is the PDF file for the CAS Server Manual book contents. It is licensed under the Apache 2.0 license."

